<!DOCTYPE html>
<html lang="ar">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>مرحبًا بك في موقع GitHub Pages</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f9;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        .content {
            text-align: center;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 0 15px rgba(0, 0, 0, 0.1);
        }
        h1 {
            color: #333;
        }
        p {
            color: #666;
        }
    </style>
</head>
<body>
    <div class="content">
        <h1>مرحبًا بك في موقع GitHub Pages!</h1>
        <p>هذه الصفحة هي جزء من المستودع الذي تم نشره عبر GitHub Pages.</p>
        <p>يمكنك تخصيص هذه الصفحة وتحديثها حسب احتياجاتك.</p>
    </div>
</body>
</html>
